package task.integer.jpa;

import org.hibernate.HibernateException;
import org.hibernate.engine.spi.SharedSessionContractImplementor;
import org.hibernate.id.IdentifierGenerator;

import java.io.Serializable;

public class CustomReportItemIdGenerator implements IdentifierGenerator {

    @Override
    public Serializable generate(SharedSessionContractImplementor sharedSessionContractImplementor, Object o) throws HibernateException {
//        SensorReportItem item = (SensorReportItem)o;
        // TODO: (as a further improvement) implement custom id generation
        // (to prevent multiple inserts of the same item for one report [which can happen
        //  as of several processings of same input file, as item Id is autogenerated])
        return null;
    }

}
